eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9101/eureka
server:
  port: 8090
spring:
  data:
    mongodb:
      database: amisno
      host: localhost
      password: amisno
      port: 27017
      username: amisno
  jackson:
    date-format: io.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
springfox:
  documentation:
    open-api:
      v3:
        path: /api-docs